### ISSUE TITLE
Add a package or support for the AnalogJS Meta Framework

### ISSUE THREAD

**Issue by SemmelJochen** [auth0/auth0-angular#612]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-angular#readme), [Examples](https://github.com/auth0/auth0-angular/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-angular/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-angular/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-angular/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am trying to setup a new application using AnalogJs. I just tried adding the auth0/angular package and setup as advised in the auth0 docs, but the Login does not work properly. 
When calling loginWithRedirect() I am able to log in in the Logs I can see a Login Event but no more. In my Application I am not able to use the isAuthenticated and user$ because they are always "false" and "null".
<img width="1134" alt="Screenshot 2024-06-08 at 20 15 50" src="https://github.com/auth0/auth0-angular/assets/43446941/d54a4843-78f0-44c2-b199-eb67ba172abc">

In my network tab I can see the following session being set:
<img width="935" alt="Screenshot 2024-06-08 at 20 18 50" src="https://github.com/auth0/auth0-angular/assets/43446941/fc9d65b0-8c93-48d6-8e93-e20ce5b25d0d">

I also tried the SPA and Regular Web App setup.

### Describe the ideal solution

I want to be able to use the auth0 package within my AnalogJs setup

**Comment by frederikprijck** [comment]
Can you share minimal reproduction so we can look into what's going on?

**Comment by SemmelJochen** [comment]
@frederikprijck u can use my test for this.
https://github.com/SemmelJochen/nx-coffeelogger-test

**Comment by frederikprijck** [comment]
@SemmelJochen can you please explain where to find the relevant code and how to reproduce? Thanks.

**Comment by SemmelJochen** [comment]
@frederikprijck sorry, about that.
To reproduce. Checkout the repo, npm i (or bun),  run "nx serve coffeelogger". Then you login with your Github Account (app must run on localhost:4200 but its default anyway). Then you will be forwarded to the app again and you can see in the logs, that no user will be available.
Relevant code:
 - [login method](https://github.com/SemmelJochen/nx-coffeelogger-test/blob/aea40779009cc0a6394aff0d79a876a97528b370/apps/coffeelogger/src/app/components/auth/login.component.ts#L20)
-  [auth0 configuration](https://github.com/SemmelJochen/nx-coffeelogger-test/blob/aea40779009cc0a6394aff0d79a876a97528b370/apps/coffeelogger/src/app/app.config.ts#L13)

Tell me if im missing something :)

**Comment by frederikprijck** [comment]
Can you confirm that after logging in, the URL still contains `code` and `state` query parameters?

If so, can you try and inject AuthService in AppComponent (no need to use it, just inject it) and see if it behaves different?

Additionally, our SDK is build on top of the Angular Router, see https://github.com/auth0/auth0-angular/blob/main/projects/auth0-angular/src/lib/abstract-navigator.ts. So it may be needed to provide your own AbstractNavigator as well.

**Comment by yogeshchoudhary147** [comment]
Hey @SemmelJochen, did you ever get this working or find a fix?

**Comment by yogeshchoudhary147** [comment]
Thanks for the discussion here. Closing this due to prolonged inactivity with no resolution. If you're still experiencing this, please open a new issue with a minimal reproduction and we'll revisit.
